// Places the sound effects on the film clock. Writes data/sfx.json, which build_timeline.mjs turns
// into <audio> elements.
//
// Usage (from video/hf-presentation):  node tools/build_sfx.mjs   (after build_timeline.mjs has run once)
//
// The clicks are not guessed: every click in the film is a click that really happened in the
// recording. capture.mjs stamped each one in raw recording seconds, build_footage.mjs recorded where
// every raw range landed on its clip's clock, and scenes.json says where each clip sits in its scene,
// so a raw click maps straight through to a film timestamp.
//
// Mix rules from the brief: effects stay at least 12 dB under the narration, and nothing fires in the
// first 0.3 s of a spoken sentence — an event that lands there is dropped rather than nudged, so a
// click never drifts away from the button it belongs to.
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const RAW = process.env.FNV_RAW || path.join(os.tmpdir(), "fnv-presentation-raw");
const plan = JSON.parse(fs.readFileSync(path.join(ROOT, "data", "plan.json"), "utf8"));
const spec = JSON.parse(fs.readFileSync(path.join(ROOT, "data", "scenes.json"), "utf8"));
const fmap = JSON.parse(fs.readFileSync(path.join(ROOT, "data", "footage_map.json"), "utf8"));
const sched = JSON.parse(fs.readFileSync(path.join(ROOT, "data", "schedule.json"), "utf8"));
const r3 = (n) => Math.round(n * 1000) / 1000;

const takeMeta = (take) => {
  const f = path.join(RAW, take, "frames", "meta.json");
  return fs.existsSync(f) ? JSON.parse(fs.readFileSync(f, "utf8")) : null;
};

/** raw recording seconds -> seconds on that clip's own clock, or null if the range was cut. */
function rawToClip(clipName, raw) {
  for (const p of fmap[clipName].pieces) {
    if (p.from == null) continue;
    if (raw >= p.from && raw <= p.to) return r3(p.t0 + (raw - p.from) / p.speed);
  }
  return null;
}

/** Where a scene starts on the film clock. */
const sceneStart = (id) => sched.scenes.find((s) => s.id === id).start;

const events = [];
const add = (sound, t, why) => { if (t != null && t >= 0) events.push({ sound, t: r3(t), why }); };

// ── scene changes ──────────────────────────────────────────────────────────
for (const sc of sched.scenes.slice(1)) add("whoosh", sc.start - 0.12, `scene ${sc.id}`);

// ── clicks and verdicts, read back out of the recordings ───────────────────
const CHIME_MARKS = new Set(["result_top", "cache_chip", "vector_chip", "url_result", "search_results"]);
for (const sc of spec.scenes) {
  for (const p of sc.panels) {
    const clip = plan.footage[p.clip];
    const meta = takeMeta(clip.take);
    if (!meta) { console.warn(`! no raw meta for take ${clip.take}; skipping its effects`); continue; }
    const base = sceneStart(sc.id) + (typeof p.in === "number" ? p.in : 0);
    for (const m of meta.marks) {
      if (m.kind === "click") {
        const c = rawToClip(p.clip, m.t);
        add("click", c == null ? null : base + c, `${p.clip} click @raw ${m.t}`);
      } else if (m.kind === "mark" && CHIME_MARKS.has(m.label)) {
        const c = rawToClip(p.clip, m.t);
        add("chime", c == null ? null : base + c - 0.12, `${p.clip} ${m.label}`);
      }
    }
  }
}

// ── the three progress steps (檢查快取 → 讀取內容 → AI 判讀) ──────────────
// They advance inside the accelerated waiting stretch of the `check` clip; one tick per step,
// spread across that stretch rather than pinned to a frame-exact moment.
{
  const base = sceneStart("s03-check");
  const fast = fmap.check.pieces.find((x) => x.speed === 3);
  if (fast) {
    const span = fast.t1 - fast.t0;
    [0.12, 0.45, 0.78].forEach((k, i) => add("tick", base + fast.t0 + span * k, `progress step ${i + 1}`));
  }
}

// ── drop anything that would land on the front of a spoken sentence ────────
const blocked = sched.cues.map((c) => [c.start - 0.05, c.start + 0.3]);
const kept = events
  .filter((e) => !blocked.some(([a, b]) => e.t >= a && e.t <= b))
  .sort((a, b) => a.t - b.t);
const dropped = events.length - kept.length;

// collapse two identical effects firing within 0.2 s of each other
const out = [];
for (const e of kept) {
  const last = out[out.length - 1];
  if (last && last.sound === e.sound && e.t - last.t < 0.2) continue;
  out.push(e);
}

fs.writeFileSync(path.join(ROOT, "data", "sfx.json"), JSON.stringify({
  _doc: "GENERATED by tools/build_sfx.mjs. t = seconds on the film clock. Clicks and chimes are mapped from the real marks in the live-site recordings; whooshes follow the scene list; ticks follow the accelerated wait in shot 3. Events inside the first 0.3 s of a narration cue were dropped.",
  gain: { click: 0.5, tick: 0.55, chime: 0.42, whoosh: 0.38 },
  events: out,
}, null, 1) + "\n", "utf8");

const byKind = {};
for (const e of out) byKind[e.sound] = (byKind[e.sound] ?? 0) + 1;
console.log(`sfx: ${out.length} events ${JSON.stringify(byKind)} (dropped ${dropped} on sentence starts)`);
