"""
雲端資料層（Supabase Postgres + pgvector）：PgKnowledgeStore／PgTaskStore／PgAuditStore。

與本機版 PandasStore／TaskStore／AuditStore 公開方法、參數、回傳形狀相同，由
app/services/store_factory.py 依 settings.use_supabase 選用；本機版完全不受影響。

設計重點
- 連線延後：建構子不連線，第一次查詢才取 engine（app.database_sql.get_pg_engine）並確保資料表存在。
- 全部用 SQLAlchemy Core text() + 綁定參數；資料表／欄位名稱只來自本檔常數，使用者內容一律走參數。
- 向量以 pgvector 文字格式 '[0.1,0.2,...]' 傳入再 CAST(... AS vector)；維度不是 1536（或含 NaN／inf）
  的向量存 NULL。相似度 = 1 - (content_vector <=> query)（cosine distance）。
- seq（identity）保存「寫入順序」，對應 Parquet 的列順序：同 hash／同網址取第一筆、任務修剪從最舊砍起。
- 時間一律 timestamp without time zone（naive）：與本機版存的值相同
  （知識庫 datetime.now()、任務／稽核 datetime.utcnow()）。
- 每個操作都是單一陳述式，走 AUTOCOMMIT 連線（省 BEGIN／COMMIT 兩趟往返）。
- 這些方法都是阻塞 IO：async 程式碼要用 asyncio.to_thread 呼叫（CLAUDE.md §7）。
"""
from __future__ import annotations

import json
import math
import threading
import uuid
import weakref
from datetime import datetime, timezone
from typing import Any, Dict, Iterable, List, Optional, Tuple

import numpy as np
import pandas as pd
from sqlalchemy import text
from sqlalchemy.engine import Connection, Engine

from app.services import task_store as _ts
from app.services.pandas_store import KB_COLUMNS, NEIGHBOR_COLUMNS, build_kb_record

VECTOR_DIM = 1536

# ── 資料表定義（全部 idempotent）───────────────────────────────────────────
_DDL_STATEMENTS = (
    """
    CREATE TABLE IF NOT EXISTS knowledge_base (
        seq                 BIGINT GENERATED BY DEFAULT AS IDENTITY,
        id                  TEXT PRIMARY KEY,
        data_type           TEXT,
        source_url          TEXT,
        raw_content         TEXT,
        data_hash           TEXT,
        content_vector      vector(1536),
        is_risk             BOOLEAN NOT NULL DEFAULT FALSE,
        risk_type           TEXT,
        category            TEXT,
        confidence_score    DOUBLE PRECISION,
        summary             TEXT,
        explanation         TEXT,
        sources             JSONB NOT NULL DEFAULT '[]',
        ai_analysis         JSONB,
        created_at          TIMESTAMP,
        last_accessed_at    TIMESTAMP,
        hit_count           INTEGER NOT NULL DEFAULT 1,
        label_source        TEXT NOT NULL DEFAULT 'ai',
        origin              TEXT NOT NULL DEFAULT 'web',
        last_result_id      TEXT,
        source_tier         INTEGER,
        verified            BOOLEAN NOT NULL DEFAULT FALSE,
        related_discussions TEXT
    )
    """,
    "CREATE INDEX IF NOT EXISTS ix_knowledge_base_data_hash ON knowledge_base (data_hash)",
    "CREATE INDEX IF NOT EXISTS ix_knowledge_base_source_url ON knowledge_base (source_url)",
    "CREATE INDEX IF NOT EXISTS ix_knowledge_base_seq ON knowledge_base (seq)",
    """
    CREATE TABLE IF NOT EXISTS tasks (
        seq                 BIGINT GENERATED BY DEFAULT AS IDENTITY,
        id                  TEXT PRIMARY KEY,
        task_type           TEXT,
        input_data          TEXT,
        status              TEXT,
        result_data         TEXT,
        error_message       TEXT,
        created_at          TIMESTAMP,
        updated_at          TIMESTAMP,
        completed_at        TIMESTAMP,
        input_type          TEXT,
        origin              TEXT NOT NULL DEFAULT 'web',
        threads_mention_id  TEXT,
        threads_reply_id    TEXT,
        platform_post       TEXT,
        ai_unavailable      BOOLEAN NOT NULL DEFAULT FALSE,
        label_source        TEXT NOT NULL DEFAULT 'ai',
        kb_id               TEXT,
        verified            BOOLEAN NOT NULL DEFAULT FALSE,
        source_tier         INTEGER,
        related_discussions TEXT
    )
    """,
    "CREATE INDEX IF NOT EXISTS ix_tasks_seq ON tasks (seq)",
    "CREATE INDEX IF NOT EXISTS ix_tasks_status ON tasks (status)",
    """
    CREATE TABLE IF NOT EXISTS admin_overrides (
        seq                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
        id                   TEXT PRIMARY KEY,
        task_id              TEXT,
        new_risk_type        TEXT,
        new_category         TEXT,
        new_confidence_score DOUBLE PRECISION,
        admin_id             TEXT,
        reason               TEXT,
        created_at           TIMESTAMP
    )
    """,
    "CREATE INDEX IF NOT EXISTS ix_admin_overrides_task_id ON admin_overrides (task_id)",
    """
    CREATE TABLE IF NOT EXISTS user_feedback (
        seq        BIGINT GENERATED BY DEFAULT AS IDENTITY,
        id         TEXT PRIMARY KEY,
        task_id    TEXT,
        user_id    TEXT,
        rating     TEXT,
        comment    TEXT,
        created_at TIMESTAMP
    )
    """,
    "CREATE INDEX IF NOT EXISTS ix_user_feedback_task_id ON user_feedback (task_id)",
)

OVERRIDE_COLUMNS = [
    "id", "task_id", "new_risk_type", "new_category",
    "new_confidence_score", "admin_id", "reason", "created_at",
]
FEEDBACK_COLUMNS = ["id", "task_id", "user_id", "rating", "comment", "created_at"]
FACT_CHECK_COLUMNS = [
    "id", "source_url", "news_title", "content", "ai_score", "ai_summary", "risk_type",
    "category", "is_trending", "created_at", "updated_at", "platform", "post_id",
    "label_source", "result_id", "verified", "source_tier",
]
TASK_COLUMNS = list(_ts._ALL_COLUMNS)

# 表名 → (欄位, 需要 CAST 的欄位)。scripts/migrate_to_supabase.py 的 upsert 也用這份。
TABLE_SPECS: Dict[str, Dict[str, Any]] = {
    "knowledge_base": {
        "columns": list(KB_COLUMNS),
        "casts": {"content_vector": "vector", "sources": "jsonb", "ai_analysis": "jsonb"},
    },
    "tasks": {"columns": TASK_COLUMNS, "casts": {}},
    "admin_overrides": {"columns": OVERRIDE_COLUMNS, "casts": {}},
    "user_feedback": {"columns": FEEDBACK_COLUMNS, "casts": {}},
    "fact_check_records": {"columns": FACT_CHECK_COLUMNS, "casts": {}},
}
ALL_TABLES = tuple(TABLE_SPECS)

# 讀知識庫列時的欄位（向量另外處理：每筆約 19 KB，沒有呼叫端需要就不傳）
_KB_READ_COLUMNS = [c for c in KB_COLUMNS if c != "content_vector"]
_KB_READ_SQL = ", ".join(_KB_READ_COLUMNS)

_ENSURED: "weakref.WeakSet[Engine]" = weakref.WeakSet()
_ENSURE_LOCK = threading.Lock()


def ensure_pg_schema(engine: Engine, force: bool = False) -> None:
    """
    pgvector 擴充 + 五張資料表（knowledge_base／tasks／admin_overrides／user_feedback／
    fact_check_records），全部 idempotent。同一個 engine 每個行程只跑一次（force=True 例外）。

    - Supabase 慣例：擴充裝在 extensions schema（連線的 search_path 已含 extensions，見 database_sql）。
    - fact_check_records 沿用既有 SQLAlchemy model；是否已存在只看「目前 schema」，不用 create_all 的
      可見性檢查（search_path 後段的 public 若已有同名表，會被誤判為已存在而不建）。
    - 啟用 RLS 且不建任何 policy：Supabase 會把 public schema 的表經 Data API 開放給 anon 金鑰，
      後端以資料表擁有者身分連線，不受 RLS 影響。
    """
    with _ENSURE_LOCK:
        if not force and engine in _ENSURED:
            return
        from app.models.fact_check_record import FactCheckRecord

        with engine.begin() as conn:
            has_extensions_schema = conn.exec_driver_sql(
                "SELECT 1 FROM pg_namespace WHERE nspname = 'extensions'"
            ).first() is not None
            conn.exec_driver_sql(
                "CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA "
                + ("extensions" if has_extensions_schema else "public")
            )
            for statement in _DDL_STATEMENTS:
                conn.exec_driver_sql(statement)
            has_fact_check = conn.exec_driver_sql(
                "SELECT to_regclass(quote_ident(current_schema()) || '.fact_check_records') IS NOT NULL"
            ).scalar()
            if not has_fact_check:
                FactCheckRecord.__table__.create(bind=conn, checkfirst=False)
            without_rls = conn.exec_driver_sql(
                "SELECT c.relname FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace "
                "WHERE n.nspname = current_schema() AND c.relkind = 'r' "
                "AND NOT c.relrowsecurity AND c.relname = ANY(%s)",
                (list(ALL_TABLES),),
            ).scalars().all()
            for table in without_rls:
                if table in ALL_TABLES:
                    conn.exec_driver_sql(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        _ENSURED.add(engine)


# ── 值的正規化（numpy／pandas → Python 原生型別；Postgres 不收 NUL 與 NaN）──────────
def _is_missing(value: Any) -> bool:
    if value is None or value is pd.NaT:
        return True
    if isinstance(value, (list, tuple, dict, set, np.ndarray)):
        return False
    try:
        return bool(pd.isna(value))
    except (TypeError, ValueError):
        return False


def _clean_text(value: Any) -> Optional[str]:
    if _is_missing(value):
        return None
    return str(value).replace("\x00", "")


def _as_float(value: Any) -> Optional[float]:
    if _is_missing(value):
        return None
    try:
        number = float(value)
    except (TypeError, ValueError):
        return None
    return number if math.isfinite(number) else None


def _as_int(value: Any) -> Optional[int]:
    number = _as_float(value)
    return int(number) if number is not None else None


def _as_bool(value: Any, default: bool = False) -> bool:
    return default if _is_missing(value) else bool(value)


def _as_datetime(value: Any) -> Optional[datetime]:
    """naive datetime（時區資訊一律先轉 UTC 再去掉）；無法解析 → None。"""
    if _is_missing(value):
        return None
    if isinstance(value, np.datetime64):
        value = pd.Timestamp(value)
    if isinstance(value, pd.Timestamp):
        value = value.to_pydatetime(warn=False)
    if isinstance(value, str):
        try:
            value = datetime.fromisoformat(value.strip())
        except ValueError:
            return None
    if not isinstance(value, datetime):
        return None
    if value.tzinfo is not None:
        value = value.astimezone(timezone.utc).replace(tzinfo=None)
    return value


def _jsonable(value: Any) -> Any:
    """遞迴轉成可存 jsonb 的純 Python 物件（ndarray → list、NaN → null、字串去 NUL）。"""
    if isinstance(value, dict):
        return {str(k).replace("\x00", ""): _jsonable(v) for k, v in value.items()}
    if isinstance(value, np.ndarray):
        return [_jsonable(v) for v in value.tolist()]
    if isinstance(value, (list, tuple, set)):
        return [_jsonable(v) for v in value]
    if isinstance(value, np.generic):
        return _jsonable(value.item())
    if _is_missing(value):
        return None
    if isinstance(value, bool):
        return value
    if isinstance(value, float):
        return value if math.isfinite(value) else None
    if isinstance(value, int):
        return value
    if isinstance(value, datetime):
        return value.isoformat()
    return str(value).replace("\x00", "")


def _to_json(value: Any) -> Optional[str]:
    if _is_missing(value):
        return None
    return json.dumps(_jsonable(value), ensure_ascii=False)


def _drop_none_keys(sources: Any) -> List[Any]:
    """Parquet 的 struct 會替每筆來源補上其他列才有的鍵（值為 None）；jsonb 不需要這些佔位。"""
    cleaned = []
    for item in _jsonable(sources) or []:
        cleaned.append({k: v for k, v in item.items() if v is not None} if isinstance(item, dict) else item)
    return cleaned


def vector_literal(vector: Any) -> Optional[str]:
    """pgvector 文字格式；None／空／維度不是 1536／含 NaN、inf → None（存 NULL、不參與比對）。"""
    if vector is None:
        return None
    try:
        with np.errstate(over="ignore", invalid="ignore"):
            arr = np.asarray(vector, dtype=np.float32)   # pgvector 以 float4 儲存；本機版也用 float32 比對
    except (TypeError, ValueError):
        return None
    if arr.ndim != 1 or arr.shape[0] != VECTOR_DIM or not np.isfinite(arr).all():
        return None
    return "[" + ",".join(format(x, ".9g") for x in arr.tolist()) + "]"


def kb_row_params(record: Dict[str, Any]) -> Dict[str, Any]:
    """KB_COLUMNS 形狀的 dict（Python／numpy／pandas 值皆可）→ INSERT 綁定參數。"""
    ai_analysis = record.get("ai_analysis")
    if isinstance(ai_analysis, dict):
        ai_analysis = dict(ai_analysis)
        if "sources" in ai_analysis:
            ai_analysis["sources"] = _drop_none_keys(ai_analysis.get("sources"))
    related = record.get("related_discussions")
    if not _is_missing(related) and not isinstance(related, str):
        related = _to_json(related)
    hit_count = _as_int(record.get("hit_count"))
    return {
        "id": _clean_text(record.get("id")),
        "data_type": _clean_text(record.get("data_type")),
        "source_url": _clean_text(record.get("source_url")),
        "raw_content": _clean_text(record.get("raw_content")),
        "data_hash": _clean_text(record.get("data_hash")),
        "content_vector": vector_literal(record.get("content_vector")),
        "is_risk": _as_bool(record.get("is_risk")),
        "risk_type": _clean_text(record.get("risk_type")),
        "category": _clean_text(record.get("category")),
        "confidence_score": _as_float(record.get("confidence_score")),
        "summary": _clean_text(record.get("summary")),
        "explanation": _clean_text(record.get("explanation")),
        "sources": json.dumps(_drop_none_keys(record.get("sources")), ensure_ascii=False),
        "ai_analysis": _to_json(ai_analysis),
        "created_at": _as_datetime(record.get("created_at")),
        "last_accessed_at": _as_datetime(record.get("last_accessed_at")),
        "hit_count": hit_count if hit_count is not None else 1,
        "label_source": _clean_text(record.get("label_source")) or "ai",
        "origin": _clean_text(record.get("origin")) or "web",
        "last_result_id": _clean_text(record.get("last_result_id")),
        "source_tier": _as_int(record.get("source_tier")),
        "verified": _as_bool(record.get("verified")),
        "related_discussions": _clean_text(related),
    }


_TASK_BOOL_COLUMNS = ("ai_unavailable", "verified")
_TASK_INT_COLUMNS = ("source_tier",)
_TASK_TEXT_DEFAULTS = {"origin": "web", "label_source": "ai"}   # NOT NULL 欄位：None → 預設（同本機載入規則）


def task_value(key: str, value: Any) -> Any:
    """tasks 欄位值 → 綁定參數；JSON 欄位的 dict／list 先序列化成字串（與本機 _encode_value 相同）。"""
    value = _ts._encode_value(key, value)
    if key in _ts._DATETIME_COLUMNS:
        return _as_datetime(value)
    if key in _TASK_BOOL_COLUMNS:
        return _as_bool(value)
    if key in _TASK_INT_COLUMNS:
        return _as_int(value)
    if isinstance(value, (dict, list, tuple, np.ndarray)):
        value = _to_json(value)
    if _is_missing(value):
        return _TASK_TEXT_DEFAULTS.get(key)
    return _clean_text(value)


def task_row_params(record: Dict[str, Any]) -> Dict[str, Any]:
    params = {col: task_value(col, record.get(col)) for col in TASK_COLUMNS}
    if not params.get("input_type"):
        params["input_type"] = _ts.input_type_from_task_type(params.get("task_type"))
    return params


def audit_row_params(record: Dict[str, Any], columns: Iterable[str]) -> Dict[str, Any]:
    params: Dict[str, Any] = {}
    for col in columns:
        value = record.get(col)
        if col == "created_at":
            params[col] = _as_datetime(value)
        elif col == "new_confidence_score":
            params[col] = _as_float(value)
        else:
            params[col] = _clean_text(value)
    return params


def fact_check_row_params(record: Dict[str, Any]) -> Dict[str, Any]:
    """SQLite 列（bool 是 0/1、時間是字串）→ Postgres 綁定參數。"""
    params: Dict[str, Any] = {}
    for col in FACT_CHECK_COLUMNS:
        value = record.get(col)
        if col in ("created_at", "updated_at"):
            params[col] = _as_datetime(value)
        elif col == "is_trending":
            params[col] = _as_bool(value)
        elif col == "verified":
            params[col] = None if _is_missing(value) else bool(value)
        elif col == "ai_score":
            params[col] = _as_float(value)
        elif col == "source_tier":
            params[col] = _as_int(value)
        else:
            params[col] = _clean_text(value)
    return params


def _placeholders(table: str) -> str:
    spec = TABLE_SPECS[table]
    return ", ".join(
        f"CAST(:{c} AS {spec['casts'][c]})" if c in spec["casts"] else f":{c}" for c in spec["columns"]
    )


def insert_statement(table: str):
    columns = TABLE_SPECS[table]["columns"]
    return text(f"INSERT INTO {table} ({', '.join(columns)}) VALUES ({_placeholders(table)})")


def upsert_statement(table: str, update_existing: bool = True):
    """
    以主鍵 id upsert。update_existing=True：只有內容不同的既有列才更新
    （ROW(...) IS DISTINCT FROM ROW(EXCLUDED...)），所以重跑一次不會動到任何列。
    """
    columns = TABLE_SPECS[table]["columns"]
    sql = f"INSERT INTO {table} ({', '.join(columns)}) VALUES ({_placeholders(table)}) ON CONFLICT (id) "
    if not update_existing:
        return text(sql + "DO NOTHING")
    data_columns = [c for c in columns if c != "id"]
    assignments = ", ".join(f"{c} = EXCLUDED.{c}" for c in data_columns)
    current = ", ".join(f"{table}.{c}" for c in data_columns)
    incoming = ", ".join(f"EXCLUDED.{c}" for c in data_columns)
    return text(
        sql + f"DO UPDATE SET {assignments} WHERE ROW({current}) IS DISTINCT FROM ROW({incoming})"
    )


# ── 共用：延後取得 engine ─────────────────────────────────────────────────
class _PgStoreBase:
    def __init__(self, engine: Optional[Engine] = None) -> None:
        self._engine = engine
        self._autocommit_engine: Optional[Engine] = None
        self._init_lock = threading.Lock()

    def _connect(self) -> Connection:
        """AUTOCOMMIT 連線；第一次呼叫才取 engine 並確保資料表存在（失敗時下次重試）。"""
        if self._autocommit_engine is None:
            with self._init_lock:
                if self._autocommit_engine is None:
                    engine = self._engine
                    if engine is None:
                        from app.database_sql import get_pg_engine
                        engine = get_pg_engine()
                    if engine.dialect.name != "postgresql":
                        raise RuntimeError("Postgres store needs a postgresql engine")
                    ensure_pg_schema(engine)
                    self._engine = engine
                    self._autocommit_engine = engine.execution_options(isolation_level="AUTOCOMMIT")
        return self._autocommit_engine.connect()


# ── 知識庫（三層快取）─────────────────────────────────────────────────────
def _like_literal(value: str) -> str:
    """ILIKE 字面比對：跳脫 \\ % _（搭配 ESCAPE '\\'），使用者輸入的 % 不會變成萬用字元。"""
    return value.replace("\\", "\\\\").replace("%", "\\%").replace("_", "\\_")


def _kb_frame(rows: List[Dict[str, Any]], include_vectors: bool = False) -> pd.DataFrame:
    """查詢結果 → 與本機版同形狀的 DataFrame（sources list、ai_analysis dict、時間 datetime64）。"""
    if not rows:
        return pd.DataFrame(columns=KB_COLUMNS)
    df = pd.DataFrame(rows, columns=KB_COLUMNS)
    df["sources"] = df["sources"].map(lambda v: v if isinstance(v, list) else [])
    if include_vectors:
        df["content_vector"] = df["content_vector"].map(
            lambda v: np.asarray(json.loads(v), dtype=np.float32) if isinstance(v, str) else None
        )
    for col in ("created_at", "last_accessed_at"):
        df[col] = pd.to_datetime(df[col], errors="coerce")
    df["is_risk"] = df["is_risk"].fillna(False).astype(bool)
    df["verified"] = df["verified"].fillna(False).astype(bool)
    df["hit_count"] = pd.to_numeric(df["hit_count"], errors="coerce").fillna(0).astype("int64")
    df["confidence_score"] = pd.to_numeric(df["confidence_score"], errors="coerce")
    df["source_tier"] = pd.to_numeric(df["source_tier"], errors="coerce")
    return df


def _kb_row(mapping: Any) -> Dict[str, Any]:
    row = dict(mapping)
    row.pop("similarity", None)
    if row.get("sources") is None:
        row["sources"] = []
    row.setdefault("content_vector", None)   # find_* 不載入向量（沒有呼叫端使用）
    return {col: row.get(col) for col in KB_COLUMNS}


class PgKnowledgeStore(_PgStoreBase):
    """PandasStore 的 Postgres 版（knowledge_base 表）。"""

    def _touch_first(self, column: str, value: str) -> Optional[Dict[str, Any]]:
        # column 只會是下面兩個常數之一；命中即 hit_count + 1（單一陳述式、一趟往返）
        statement = text(
            f"UPDATE knowledge_base SET hit_count = hit_count + 1, last_accessed_at = :now "
            f"WHERE id = (SELECT id FROM knowledge_base WHERE {column} = :value ORDER BY seq LIMIT 1) "
            f"RETURNING {_KB_READ_SQL}"
        )
        with self._connect() as conn:
            row = conn.execute(statement, {"now": datetime.now(), "value": value}).mappings().first()
        return _kb_row(row) if row is not None else None

    # Layer 0
    def find_by_url(self, url: str) -> Optional[Dict[str, Any]]:
        """以來源 URL 查找快取（同網址多筆取最早寫入者），命中時更新 hit_count。"""
        if _is_missing(url):
            return None
        return self._touch_first("source_url", str(url))

    # Layer 1
    def find_by_hash(self, content_hash: str) -> Optional[Dict[str, Any]]:
        """根據 SHA-256 Hash 查找快取（同 hash 多筆取最早寫入者）。"""
        if _is_missing(content_hash):
            return None
        return self._touch_first("data_hash", str(content_hash))

    # Layer 2
    def find_similar_by_vector(
        self,
        query_vector: List[float],
        threshold: Optional[float] = None,
        label_sources: Optional[Iterable[str]] = None,
    ) -> Optional[Dict[str, Any]]:
        """
        cosine similarity 最高且 >= threshold 的「verified」列（FR-17）；threshold 預設
        settings.SIMILARITY_THRESHOLD。空向量／零向量／維度不符 → None（不查資料庫）。
        label_sources：只比對這些 label_source 的列（None = 不限），與本機版相同。
        """
        if threshold is None:
            from app.config import settings
            threshold = settings.SIMILARITY_THRESHOLD
        if query_vector is None or len(query_vector) == 0:
            return None
        literal = vector_literal(query_vector)
        if literal is None or not np.any(np.asarray(query_vector, dtype=np.float32)):
            return None

        label_filter = "" if label_sources is None else "  AND label_source = ANY(:labels)"
        returning = ", ".join(f"kb.{c}" for c in _KB_READ_COLUMNS)
        statement = text(
            "WITH best AS ("
            "  SELECT id, 1 - (content_vector <=> CAST(:q AS vector)) AS similarity"
            "  FROM knowledge_base"
            "  WHERE verified AND content_vector IS NOT NULL"
            f"{label_filter}"
            "  ORDER BY content_vector <=> CAST(:q AS vector), seq"
            "  LIMIT 1"
            ") "
            "UPDATE knowledge_base AS kb"
            " SET hit_count = kb.hit_count + 1, last_accessed_at = :now"
            " FROM best"
            # 零向量列的 cosine distance 是 NaN；Postgres 視 NaN 大於任何數，要另外擋掉
            " WHERE kb.id = best.id AND best.similarity >= :threshold"
            "   AND best.similarity <> CAST('NaN' AS double precision)"
            f" RETURNING {returning}, best.similarity"
        )
        params = {"q": literal, "now": datetime.now(), "threshold": float(threshold)}
        if label_sources is not None:
            params["labels"] = [str(label) for label in label_sources]
        with self._connect() as conn:
            row = conn.execute(statement, params).mappings().first()
        return _kb_row(row) if row is not None else None

    def nearest_verified(
        self,
        query_vector: List[float],
        k: int = 5,
        label_sources: Optional[Iterable[str]] = None,
    ) -> List[Dict[str, Any]]:
        """最接近的 k 筆已證實列（證據信心用；不設門檻、不更新 hit_count），與本機版相同。"""
        if query_vector is None or len(query_vector) == 0 or int(k) <= 0:
            return []
        literal = vector_literal(query_vector)
        if literal is None or not np.any(np.asarray(query_vector, dtype=np.float32)):
            return []
        label_filter = "" if label_sources is None else " AND label_source = ANY(:labels)"
        statement = text(
            f"SELECT {', '.join(NEIGHBOR_COLUMNS)}, 1 - (content_vector <=> CAST(:q AS vector)) AS similarity"
            " FROM knowledge_base WHERE verified AND content_vector IS NOT NULL"
            f"{label_filter}"
            " ORDER BY content_vector <=> CAST(:q AS vector), seq LIMIT :k"
        )
        params: Dict[str, Any] = {"q": literal, "k": int(k)}
        if label_sources is not None:
            params["labels"] = [str(label) for label in label_sources]
        with self._connect() as conn:
            rows = conn.execute(statement, params).mappings().all()
        neighbours = []
        for row in rows:
            similarity = row["similarity"]
            if similarity is None or math.isnan(float(similarity)):   # 零向量列的 cosine distance 是 NaN
                continue
            item = {col: row[col] for col in NEIGHBOR_COLUMNS}
            item["sources"] = item["sources"] or []
            item["similarity"] = float(similarity)
            neighbours.append(item)
        return neighbours

    def save_record(
        self,
        data_type: str,
        raw_content: str,
        content_hash: str,
        content_vector: Optional[List[float]] = None,
        ai_result: Optional[Dict[str, Any]] = None,
        source_url: Optional[str] = None,
        label_source: str = "ai",
        verified: Optional[bool] = None,
        origin: str = "web",
        last_result_id: Optional[str] = None,
        related_discussions: Any = None,
    ) -> Dict[str, Any]:
        record = build_kb_record(
            data_type=data_type, raw_content=raw_content, content_hash=content_hash,
            content_vector=content_vector, ai_result=ai_result, source_url=source_url,
            label_source=label_source, verified=verified, origin=origin,
            last_result_id=last_result_id, related_discussions=related_discussions,
        )
        params = self._row_params(record)
        with self._connect() as conn:
            conn.execute(insert_statement("knowledge_base"), params)
        if params["content_vector"] is None:
            record["content_vector"] = None   # 維度不是 1536：實際存的是 NULL
        return record

    def save_records(self, items: Iterable[Dict[str, Any]], batch_size: int = 200) -> int:
        """批次寫入（scripts/ingest_factchecks.py 用）：與 save_record 同一套內容，每批一次 executemany。"""
        params = [self._row_params(build_kb_record(**item)) for item in items]
        with self._connect() as conn:
            for start in range(0, len(params), batch_size):
                conn.execute(insert_statement("knowledge_base"), params[start:start + batch_size])
        return len(params)

    @staticmethod
    def _row_params(record: Dict[str, Any]) -> Dict[str, Any]:
        rd = record.get("related_discussions")
        if rd is not None and not isinstance(rd, str):
            record["related_discussions"] = json.dumps(_jsonable(rd), ensure_ascii=False)
        return kb_row_params(record)

    def get_all_records(self, include_vectors: bool = False) -> pd.DataFrame:
        """
        整張知識庫（依寫入順序），欄位與本機版相同：sources 是 list[dict]、ai_analysis 是 dict、
        related_discussions 是 JSON 字串、時間是 datetime64。content_vector 預設全為 None
        （每筆約 19 KB，API 與管理端都用不到）；include_vectors=True 才載入（np.ndarray）。
        """
        vector_sql = "CAST(content_vector AS text) AS content_vector" if include_vectors \
            else "NULL AS content_vector"
        statement = text(f"SELECT {_KB_READ_SQL}, {vector_sql} FROM knowledge_base ORDER BY seq")
        with self._connect() as conn:
            rows = [dict(r) for r in conn.execute(statement).mappings().all()]
        return _kb_frame(rows, include_vectors)

    # 知識庫頁查詢（/api/knowledge）：在資料庫裡篩選、計數與分頁，不把整張表載進記憶體
    # （2026-09 批次寫入查核機構資料後約 1.9 萬列；Render 免費主機只有 512 MB）。行為與本機版相同。
    def verified_counts(self) -> Tuple[Dict[str, int], int]:
        statement = text(
            "SELECT verified, COALESCE(NULLIF(risk_type, ''), 'UNKNOWN') AS risk, count(*) AS n"
            " FROM knowledge_base GROUP BY 1, 2"
        )
        by_risk: Dict[str, int] = {}
        unverified = 0
        with self._connect() as conn:
            for row in conn.execute(statement).mappings():
                if row["verified"]:
                    by_risk[row["risk"]] = by_risk.get(row["risk"], 0) + int(row["n"])
                else:
                    unverified += int(row["n"])
        return by_risk, unverified

    def list_verified(
        self, q: str = "", risk_type: str = "", limit: int = 30, offset: int = 0,
    ) -> Tuple[int, pd.DataFrame]:
        where, params = ["verified"], {}
        if q.strip():
            where.append("(raw_content ILIKE :q ESCAPE '\\' OR summary ILIKE :q ESCAPE '\\')")
            params["q"] = f"%{_like_literal(q.strip())}%"
        if risk_type.strip():
            where.append("upper(risk_type) = :risk")
            params["risk"] = risk_type.strip().upper()
        clause = " AND ".join(where)
        page_sql = text(
            f"SELECT {_KB_READ_SQL}, NULL AS content_vector FROM knowledge_base WHERE {clause}"
            " ORDER BY created_at DESC NULLS LAST, id ASC LIMIT :limit OFFSET :offset"
        )
        with self._connect() as conn:
            total = conn.execute(text(f"SELECT count(*) FROM knowledge_base WHERE {clause}"), params).scalar()
            rows = [dict(r) for r in conn.execute(
                page_sql, {**params, "limit": int(limit), "offset": int(offset)}).mappings().all()]
        return int(total or 0), _kb_frame(rows)

    def get_verified_by_ids(self, ids: Iterable[str]) -> pd.DataFrame:
        wanted = sorted({str(i) for i in ids if i})
        if not wanted:
            return pd.DataFrame(columns=KB_COLUMNS)
        statement = text(
            f"SELECT {_KB_READ_SQL}, NULL AS content_vector FROM knowledge_base"
            " WHERE verified AND id = ANY(:ids) ORDER BY seq"
        )
        with self._connect() as conn:
            rows = [dict(r) for r in conn.execute(statement, {"ids": wanted}).mappings().all()]
        return _kb_frame(rows)

    def apply_admin_override(self, kb_id: str, verdict: Dict[str, Any]) -> bool:
        """
        管理者覆寫（app/api/admin.py）：label_source=admin、verified=True，並把覆寫後的判定寫進
        頂層欄位與 ai_analysis（其餘鍵保留）。本機版是整檔重寫，這裡是單列 UPDATE。找不到列 → False。
        """
        converters = {
            "risk_type": _clean_text, "category": _clean_text,
            "confidence_score": _as_float, "is_risk": _as_bool,
        }
        fields = {k: convert(verdict[k]) for k, convert in converters.items() if k in verdict}
        assignments = ["label_source = 'admin'", "verified = TRUE"]
        assignments += [f"{k} = :{k}" for k in fields]
        assignments.append(
            "ai_analysis = CASE WHEN jsonb_typeof(ai_analysis) = 'object' "
            "THEN ai_analysis || CAST(:patch AS jsonb) ELSE ai_analysis END"
        )
        statement = text(f"UPDATE knowledge_base SET {', '.join(assignments)} WHERE id = :kb_id")
        patch = {k: verdict[k] for k in converters if k in verdict}
        params = {**fields, "patch": json.dumps(_jsonable(patch), ensure_ascii=False), "kb_id": str(kb_id)}
        with self._connect() as conn:
            return (conn.execute(statement, params).rowcount or 0) > 0


# ── 任務（結果頁 /r/{id} 的資料來源）──────────────────────────────────────
_TASK_SELECT_SQL = ", ".join(TASK_COLUMNS)


class PgTaskStore(_PgStoreBase):
    """TaskStore 的 Postgres 版（tasks 表）。"""

    def create_task(
        self,
        task_type: str,
        input_data: str,
        input_type: Optional[str] = None,
        origin: str = "web",
        **extra: Any,
    ) -> str:
        """建立 pending 任務；extra 只收 spec §6.1 新欄位，未知鍵忽略。超過上限時修剪（規則同本機版）。"""
        task_id = str(uuid.uuid4())
        now = datetime.utcnow()
        record: Dict[str, Any] = {
            "id": task_id,
            "task_type": task_type,
            "input_data": input_data,
            "status": "pending",
            "result_data": None,
            "error_message": None,
            "created_at": now,
            "updated_at": now,
            "completed_at": None,
        }
        record.update(_ts._NEW_COLUMN_DEFAULTS)
        record["input_type"] = input_type or _ts.input_type_from_task_type(task_type)
        record["origin"] = origin or "web"
        for key, value in extra.items():
            if key in _ts._NEW_COLUMN_DEFAULTS and key not in ("input_type", "origin"):
                record[key] = value

        # 只刪已結束（completed／failed）中最舊者；pending／processing 不砍（可暫時超過上限）
        prune = text(
            "DELETE FROM tasks WHERE id IN ("
            "  SELECT id FROM tasks WHERE status = ANY(:statuses) ORDER BY seq"
            "  LIMIT GREATEST((SELECT count(*) FROM tasks) - :cap, 0)"
            ")"
        )
        with self._connect() as conn:
            conn.execute(insert_statement("tasks"), task_row_params(record))
            conn.execute(prune, {"statuses": list(_ts._PRUNABLE_STATUSES), "cap": int(_ts._MAX_TASKS)})
        return task_id

    def update_task(self, task_id: str, **fields: Any) -> None:
        """更新任務欄位（未知欄位忽略；任務不存在時不做事）；updated_at 一律更新。"""
        values: Dict[str, Any] = {"updated_at": datetime.utcnow()}
        for key, value in fields.items():
            if key in TASK_COLUMNS:
                values[key] = task_value(key, value)
        assignments = ", ".join(f"{key} = :{key}" for key in values)
        statement = text(f"UPDATE tasks SET {assignments} WHERE id = :_task_id")
        with self._connect() as conn:
            conn.execute(statement, {**values, "_task_id": str(task_id)})

    def get_task(self, task_id: str) -> Optional[Dict[str, Any]]:
        """單一任務（時間轉 ISO 字串、布林／整數為 Python 型別；找不到 → None）。"""
        statement = text(f"SELECT {_TASK_SELECT_SQL} FROM tasks WHERE id = :task_id")
        with self._connect() as conn:
            row = conn.execute(statement, {"task_id": str(task_id)}).mappings().first()
        if row is None:
            return None
        record = dict(row)
        for key in _ts._DATETIME_COLUMNS:
            if isinstance(record.get(key), datetime):
                record[key] = record[key].isoformat()
        for key in _TASK_BOOL_COLUMNS:
            record[key] = bool(record.get(key)) if record.get(key) is not None else False
        if not record.get("input_type"):
            record["input_type"] = _ts.input_type_from_task_type(record.get("task_type"))
        return record

    def recent_kb_refs(self, since: datetime) -> List[Dict[str, Any]]:
        """since 之後建立、已完成、對應到知識庫列的任務 {kb_id, created_at, origin}（同本機版）。"""
        statement = text(
            "SELECT kb_id, created_at, origin FROM tasks"
            " WHERE status = 'completed' AND kb_id IS NOT NULL AND kb_id <> ''"
            "   AND created_at >= :since"
            " ORDER BY seq"
        )
        with self._connect() as conn:
            rows = conn.execute(statement, {"since": since}).mappings().all()
        return [
            {"kb_id": str(r["kb_id"]), "created_at": r["created_at"], "origin": r["origin"] or "web"}
            for r in rows
        ]


# ── 覆寫與回饋 ─────────────────────────────────────────────────────────────
class PgAuditStore(_PgStoreBase):
    """AuditStore 的 Postgres 版（admin_overrides／user_feedback 表）。"""

    def _append(self, table: str, columns: List[str], record: Dict[str, Any]) -> Dict[str, Any]:
        with self._connect() as conn:
            conn.execute(insert_statement(table), audit_row_params(record, columns))
        record["created_at"] = record["created_at"].isoformat()
        return record

    def _load(self, table: str, columns: List[str]) -> pd.DataFrame:
        statement = text(f"SELECT {', '.join(columns)} FROM {table} ORDER BY seq")
        with self._connect() as conn:
            rows = [dict(r) for r in conn.execute(statement).mappings().all()]
        return pd.DataFrame(rows, columns=columns)

    def _load_overrides(self) -> pd.DataFrame:
        return self._load("admin_overrides", OVERRIDE_COLUMNS)

    def _load_feedback(self) -> pd.DataFrame:
        return self._load("user_feedback", FEEDBACK_COLUMNS)

    def append_override(
        self,
        task_id: str,
        admin_id: str,
        reason: str,
        new_risk_type: Optional[str] = None,
        new_category: Optional[str] = None,
        new_confidence_score: Optional[float] = None,
    ) -> Dict[str, Any]:
        return self._append("admin_overrides", OVERRIDE_COLUMNS, {
            "id": str(uuid.uuid4()),
            "task_id": task_id,
            "new_risk_type": new_risk_type,
            "new_category": new_category,
            "new_confidence_score": new_confidence_score,
            "admin_id": admin_id,
            "reason": reason,
            "created_at": datetime.utcnow(),
        })

    def append_feedback(
        self,
        task_id: str,
        rating: str,
        comment: Optional[str] = None,
        user_id: Optional[str] = None,
    ) -> Dict[str, Any]:
        return self._append("user_feedback", FEEDBACK_COLUMNS, {
            "id": str(uuid.uuid4()),
            "task_id": task_id,
            "user_id": user_id,
            "rating": rating,
            "comment": comment,
            "created_at": datetime.utcnow(),
        })
